/*******************************************************************************
 * FreeQDA,  a software for professional qualitative research data 
 * analysis, such as interviews, manuscripts, journal articles, memos
 * and field notes.
 *
 * Copyright (C) 2011 Dirk Kitscha, Jörg große Schlarmann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.20 at 02:15:28 PM MEZ 
//


package net.sf.freeqda.bindings.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FQDAProjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FQDAProjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TagList" type="{http://sf.net.freeqda/FQDAProject}TagListType"/>
 *         &lt;element name="TextCategoryList" type="{http://sf.net.freeqda/FQDAProject}TextCategoryListType"/>
 *         &lt;element name="TextList" type="{http://sf.net.freeqda/FQDAProject}TextListType"/>
 *         &lt;element name="HighestTextUID" type="{http://sf.net.freeqda/FQDAProject}HighestTextUIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FQDAProjectType", propOrder = {
    "name",
    "tagList",
    "textCategoryList",
    "textList",
    "highestTextUID"
})
public class FQDAProjectType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "TagList", required = true)
    protected TagListType tagList;
    @XmlElement(name = "TextCategoryList", required = true)
    protected TextCategoryListType textCategoryList;
    @XmlElement(name = "TextList", required = true)
    protected TextListType textList;
    @XmlElement(name = "HighestTextUID")
    protected int highestTextUID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the tagList property.
     * 
     * @return
     *     possible object is
     *     {@link TagListType }
     *     
     */
    public TagListType getTagList() {
        return tagList;
    }

    /**
     * Sets the value of the tagList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagListType }
     *     
     */
    public void setTagList(TagListType value) {
        this.tagList = value;
    }

    /**
     * Gets the value of the textCategoryList property.
     * 
     * @return
     *     possible object is
     *     {@link TextCategoryListType }
     *     
     */
    public TextCategoryListType getTextCategoryList() {
        return textCategoryList;
    }

    /**
     * Sets the value of the textCategoryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextCategoryListType }
     *     
     */
    public void setTextCategoryList(TextCategoryListType value) {
        this.textCategoryList = value;
    }

    /**
     * Gets the value of the textList property.
     * 
     * @return
     *     possible object is
     *     {@link TextListType }
     *     
     */
    public TextListType getTextList() {
        return textList;
    }

    /**
     * Sets the value of the textList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListType }
     *     
     */
    public void setTextList(TextListType value) {
        this.textList = value;
    }

    /**
     * Gets the value of the highestTextUID property.
     * 
     */
    public int getHighestTextUID() {
        return highestTextUID;
    }

    /**
     * Sets the value of the highestTextUID property.
     * 
     */
    public void setHighestTextUID(int value) {
        this.highestTextUID = value;
    }

}
